server:
  port: 8000
  servlet:
    context-path: /myblog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: junho
    password: 1q2w3e4r!Q@W
    
  thymeleaf:
    cache: false
    prefix: /template/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false # jpa사용하는 기본 넘버링 전략을 따라가지 않는다면, false로 지정
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  